//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFBattleTester_v2.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GFBattleTester_v2.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   RX に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string indicater_rx {
            get {
                return ResourceManager.GetString("indicater_rx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TX に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string indicater_tx {
            get {
                return ResourceManager.GetString("indicater_tx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This feature is not supported yet. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string message_server_notsupported {
            get {
                return ResourceManager.GetString("message_server_notsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string notification {
            get {
                return ResourceManager.GetString("notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The client has been reset. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string reset_client {
            get {
                return ResourceManager.GetString("reset_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running server at {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string runningServer {
            get {
                return ResourceManager.GetString("runningServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Paused に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_paused {
            get {
                return ResourceManager.GetString("server_paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The server started at {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string server_started_alert {
            get {
                return ResourceManager.GetString("server_started_alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Server に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string serverstart {
            get {
                return ResourceManager.GetString("serverstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Server に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string serverstop {
            get {
                return ResourceManager.GetString("serverstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equip Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tapPage_equipsett {
            get {
                return ResourceManager.GetString("tapPage_equipsett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fairy Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tapPage_fairysett {
            get {
                return ResourceManager.GetString("tapPage_fairysett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T-Doll Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tapPage_gunsett {
            get {
                return ResourceManager.GetString("tapPage_gunsett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tapPage_info {
            get {
                return ResourceManager.GetString("tapPage_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Setting に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tapPage_serversett {
            get {
                return ResourceManager.GetString("tapPage_serversett", resourceCulture);
            }
        }
    }
}
