//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFBattleTester_v2.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GFBattleTester_v2.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   RX과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string indicater_rx {
            get {
                return ResourceManager.GetString("indicater_rx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TX과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string indicater_tx {
            get {
                return ResourceManager.GetString("indicater_tx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This feature is not supported yet.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string message_server_notsupported {
            get {
                return ResourceManager.GetString("message_server_notsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running server at {0}과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string runningServer {
            get {
                return ResourceManager.GetString("runningServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Paused과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string server_paused {
            get {
                return ResourceManager.GetString("server_paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string serverstart {
            get {
                return ResourceManager.GetString("serverstart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stop Server과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string serverstop {
            get {
                return ResourceManager.GetString("serverstop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Equip Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tapPage_equipsett {
            get {
                return ResourceManager.GetString("tapPage_equipsett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fairy Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tapPage_fairysett {
            get {
                return ResourceManager.GetString("tapPage_fairysett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   T-Doll Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tapPage_gunsett {
            get {
                return ResourceManager.GetString("tapPage_gunsett", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tapPage_info {
            get {
                return ResourceManager.GetString("tapPage_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server Setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string tapPage_serversett {
            get {
                return ResourceManager.GetString("tapPage_serversett", resourceCulture);
            }
        }
    }
}
